APIリクエストを対象としたUnitテストを実装
MachonglishproK/SkillCheckProject pull request #18
Opened 2020-12-11 09:47 UTC by MachonglishproK

## 対応内容

1. テスト用ターゲットSkillCheckProjectTestsを作成し
2. 作成したターゲットのPodファイルにOHHTTPStubsを追加
3. APIリクエストの各StatusCodeに対して、レスポンスを確認するテストを追加

レビューよろしくお願いいたします。
※テスト用のターゲットを追加するにあたり、フォルダの移動したため、変更ファイル数が多くなっています。

2020-12-11 11:40 UTC, ysk-tngc requested changes
@MachonglishproK `DataAccessTests` というフォルダとその中のファイル、未使用だと思うので削除をお願いします。

2020-12-14 01:24 UTC, MachonglishproK commented
@ysk-tngc  レビューありがとうございます。承知いたしました。削除し、追加Pushします！

2020-12-14 01:43 UTC, MachonglishproK commented
@ysk-tngc DataAccessTestsフォルダを削除しました。よろしくお願いいたします。

2020-12-14 01:59 UTC, ysk-tngc approved these changes
LGTM です

2020-12-14 01:59 UTC, merged